import { useState } from "react";
import { ExternalLink, ChartNoAxesCombined } from "lucide-react";
import { Link } from "react-router-dom";
import type { Level } from "../data/types";
import { readingGuide, type NewsArticle } from "../data/news";
import { marketLessons } from "../data/market";
import { CompanionArt } from "./Companion";
import { companions } from "../data/companions";
import { dayKey } from "../activity";
// The frame URL is generated by TradingView’s official Symbol Overview embed.
const chartUrl =
  "https://www.tradingview-widget.com/embed-widget/symbol-overview/?locale=en#" +
  encodeURIComponent(
    JSON.stringify({
      symbols: [
        ["US 500 · CFD", "FOREXCOM:SPX500|1D"],
        ["US 30 · CFD", "FOREXCOM:US30|1D"],
        ["US Tech 100 · CFD", "FOREXCOM:NAS100|1D"],
      ],
      chartOnly: false,
      width: "100%",
      height: "100%",
      colorTheme: "light",
      showVolume: false,
      showMA: false,
      hideDateRanges: false,
      hideMarketStatus: false,
      hideSymbolLogo: true,
      scalePosition: "right",
      scaleMode: "Normal",
      fontFamily: "Arial, sans-serif",
      fontSize: "12",
      noTimeScale: false,
      valuesTracking: "1",
      changeMode: "price-and-percent",
      chartType: "area",
      lineWidth: 2,
      lineColor: "#398344",
      topColor: "rgba(57, 131, 68, 0.15)",
      bottomColor: "rgba(57, 131, 68, 0.02)",
      dateRanges: ["1d|1", "5d|5", "1m|30", "12m|1D", "all|1W"],
      utm_medium: "widget_new",
      utm_campaign: "symbol-overview",
    }),
  );
function MarketWalkthrough({ level }: { level: Level }) {
  const lesson = marketLessons[level];
  const [step, setStep] = useState(0);
  const [answer, setAnswer] = useState<number | null>(null);
  return (
    <div className={`market-lesson market-lesson-${level.toLowerCase()}`}>
      <div className="market-lesson-intro">
        <CompanionArt level={level} />
        <div>
          <span>
            {companions[level].name}’s {level.toLowerCase()} walkthrough
          </span>
          <h3>{lesson.title}</h3>
          <p>{lesson.intro}</p>
        </div>
      </div>
      <div
        className="market-step-controls"
        role="group"
        aria-label={`${level} chart walkthrough steps`}
      >
        {lesson.steps.map((item, index) => (
          <button
            key={item.title}
            aria-pressed={step === index}
            onClick={() => setStep(index)}
          >
            {index + 1}. {item.title}
          </button>
        ))}
      </div>
      <div className="market-step-copy" aria-live="polite">
        <h4>{lesson.steps[step].title}</h4>
        <p>{lesson.steps[step].text}</p>
      </div>
      <details className="market-practice">
        <summary>Practice example: {level.toLowerCase()}</summary>
        <h4>{lesson.example.label}</h4>
        <p>{lesson.example.text}</p>
        <fieldset>
          <legend>{lesson.question}</legend>
          {lesson.choices.map((choice, index) => (
            <label key={choice}>
              <input
                type="radio"
                name={`market-check-${level}`}
                checked={answer === index}
                onChange={() => setAnswer(index)}
              />
              {choice}
            </label>
          ))}
        </fieldset>
        {answer !== null && (
          <p role="status" className="market-check-feedback">
            <strong>
              {answer === lesson.correct
                ? "That’s right. "
                : "Take another look. "}
            </strong>
            {lesson.feedback}
          </p>
        )}
      </details>
    </div>
  );
}
export function MarketOverview({
  level,
  articles,
  date,
}: {
  level: Level;
  articles: NewsArticle[];
  date: string;
}) {
  const [showChart, setShowChart] = useState(false);
  const context = articles
    .filter(
      (a) =>
        dayKey(new Date(a.publishedAt)) === date &&
        /market|stock|shares|earnings|inflation|rate|jobs|oil/i.test(a.title),
    )
    .slice(0, 3);
  return (
    <section className="market-overview" aria-labelledby="market-title">
      <div className="market-title-row">
        <h2 id="market-title">How’s the market doing?</h2>
        <span>TradingView charts</span>
      </div>
      <MarketWalkthrough key={level} level={level} />
      <p className="market-caption">
        {marketLessons[level].caption} Check the chart’s timestamp and range;
        the news date filter does not change them.
      </p>
      {showChart ? (
        <div className="market-chart-wrap">
          <iframe
            className="market-chart"
            src={chartUrl}
            title="Interactive U.S. market CFD proxy charts by TradingView"
            sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
            referrerPolicy="no-referrer"
          />
          <button
            className="market-hide-chart"
            onClick={() => setShowChart(false)}
          >
            Hide chart
          </button>
        </div>
      ) : (
        <div className="market-chart-choice">
          <ChartNoAxesCombined size={34} aria-hidden="true" />
          <div>
            <h3>The big picture, in one chart.</h3>
            <p>
              Loading the chart connects your browser to TradingView. They may
              process device information and use cookies under their own policy.
              Your FinancePath profile stays here.{" "}
              <Link to="/legal/privacy">Privacy details</Link>
            </p>
          </div>
          <button className="button primary" onClick={() => setShowChart(true)}>
            Show market chart
          </button>
        </div>
      )}
      <p className="market-chart-fallback">
        <a
          href="https://www.tradingview.com/markets/indices/"
          target="_blank"
          rel="noopener noreferrer"
        >
          View markets on TradingView{" "}
          <ExternalLink size={13} aria-hidden="true" />
        </a>
        <span>Use this link if the chart is blocked or unavailable.</span>
      </p>
      <details>
        <summary>{marketLessons[level].contextTitle}</summary>
        <p>
          Reporting from {date} provides context, not a verified explanation of
          a price move or a prediction. The chart’s selected session may differ
          from this article date.
        </p>
        {context.length ? (
          <ul>
            {context.map((a) => (
              <li key={a.id} className="market-news-context">
                <a href={a.url} target="_blank" rel="noopener noreferrer">
                  {a.title}
                </a>{" "}
                <span>— {a.source}</span>
                {readingGuide(a, level).map((text) => (
                  <p key={text}>{text}</p>
                ))}
              </li>
            ))}
          </ul>
        ) : (
          <p>
            No market-related reporting for this date is available in the
            collection. Look for earnings, interest-rate decisions, inflation,
            and employment releases; do not assume they explain a move without
            evidence.
          </p>
        )}
      </details>
      <p className="market-caption">
        Chart and quotes provided by TradingView. FinancePath does not copy or
        redistribute the widget’s data. For learning only; no buy or sell
        recommendations.
      </p>
    </section>
  );
}
